"use client";

import { KeyRound, Loader2, ShieldCheck } from "lucide-react";
import { useTranslations } from "next-intl";
import { useState, useTransition } from "react";
import { FormError } from "@/components/forms/form-error";
import { Button } from "@/components/ui/button";
import { Field, Input } from "@/components/ui/form-controls";
import type { DomainErrorCode } from "@/lib/errors";
import { startTotpEnrollmentAction, verifyTotpAction } from "./mfa-actions";

/** Enrolls or verifies a TOTP authenticator; on success the session is upgraded to aal2. */
export function MfaPanel({ verifiedFactorId, next }: { verifiedFactorId: string | null; next: string }) {
  const t = useTranslations("admin.mfa");
  const [enrollment, setEnrollment] = useState<{ factorId: string; qrCode: string; secret: string } | null>(null);
  const [code, setCode] = useState("");
  const [error, setError] = useState<DomainErrorCode | null>(null);
  const [pending, startTransition] = useTransition();
  const factorId = verifiedFactorId ?? enrollment?.factorId ?? null;

  function enroll() {
    setError(null);
    startTransition(async () => {
      const result = await startTotpEnrollmentAction();
      if (result.ok) {
        setEnrollment(result.data);
      } else {
        setError(result.error);
      }
    });
  }

  function verify(event: React.FormEvent) {
    event.preventDefault();
    if (!factorId) {
      return;
    }
    setError(null);
    startTransition(async () => {
      const result = await verifyTotpAction(factorId, code);
      if (!result.ok) {
        setError(result.error);
        setCode("");
        return;
      }
      // Full navigation so every request uses the upgraded session cookies.
      window.location.assign(next);
    });
  }

  return (
    <div className="flex flex-col gap-5">
      <FormError code={error} />
      {!factorId ? (
        <div className="flex flex-col items-start gap-3">
          <p className="text-sm text-muted-foreground">{t("setupText")}</p>
          <Button onClick={enroll} disabled={pending}>
            {pending ? <Loader2 className="animate-spin" aria-hidden="true" /> : <ShieldCheck aria-hidden="true" />}
            {t("setup")}
          </Button>
        </div>
      ) : null}
      {enrollment ? (
        <div className="flex flex-col gap-3">
          <p className="text-sm">{t("scanText")}</p>
          {/* eslint-disable-next-line @next/next/no-img-element -- data: URI SVG generated by Supabase Auth */}
          <img
            src={enrollment.qrCode}
            alt={t("qrAlt")}
            className="size-48 rounded-xl border border-border bg-white p-2"
          />
          <p className="text-sm text-muted-foreground">{t("secretText")}</p>
          <p className="rounded-lg bg-muted p-2 font-mono text-sm break-all">{enrollment.secret}</p>
        </div>
      ) : null}
      {factorId ? (
        <form onSubmit={verify} className="flex flex-col gap-3">
          <Field id="totp-code" label={t("codeLabel")} hint={t("codeHint")}>
            <Input
              id="totp-code"
              value={code}
              onChange={(e) => setCode(e.target.value)}
              inputMode="numeric"
              autoComplete="one-time-code"
              pattern="\d{6}"
              maxLength={6}
              required
              className="w-40 font-mono text-lg tracking-widest"
            />
          </Field>
          <div>
            <Button type="submit" disabled={pending || code.length !== 6}>
              {pending ? <Loader2 className="animate-spin" aria-hidden="true" /> : <KeyRound aria-hidden="true" />}
              {t("verify")}
            </Button>
          </div>
        </form>
      ) : null}
    </div>
  );
}
